### PR TITLE
Rewrite and Update ViaProxy to 3.3.7

### PR DESCRIPTION
**Pull request by ShayBox**
I tried to rewrite the plugin to fix it, but I still get the same error  
`system did not run because it requested inaccessible system parameter ...`
`Res<Swarm>` and `Res<Events<LoginPacketEvent>>`

image

### CODE REVIEW

**Comment by ShayBox** [comment]
The reason I rewrote this was because I didn't realize my error was because this plugin uses upstream azalea and I was using my fork, which causes silent type conflicts with resources not existing.

Anyway, this is done and works, I updated the ViaProxy version, added the new Open Auth Mod plugin, added support for Java 8, 17, and 21 (tested), and updated the host name with the help of the ViaProxy dev.

I learned you can patch dependencies of dependencies, just make sure you use `azalea-rs/azalea` for both `azalea` and `azalea-viaversion` and this patch replaces it with a fork.
```toml
[patch.'https://github.com/azalea-rs/azalea']
azalea = { git = "https://github.com/Shays-Forks/azalea" }
```

EDIT: I realized Bevy Tasks doesn't work because Azalea doesn't use it, it relies on Tokio (maybe others), so I switched to a tokio task, should Azalea switch to Bevy Tasks for async?

**Comment by ShayBox** [comment]
Fixes #8

**Review by mat-1 — COMMENTED** [review]
I'm usually not a fan of rewrites like this and skimming through the diff I'll note that there's some things I'd change (like remove the `#[macro_use] extern crate` statements and changing some comments), but.. if you're willing to take over maintainership of this crate (since I haven't been maintaining it well anyways) I can merge as-is and give you maintain permissions if you want.

**Comment by ShayBox** [comment]
I can maintain this, but if there's any changes you'd make I can change them

**Pull request merged**
